server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.115.177.10:3306/plus?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  redis:
    host: 47.115.177.10
    port: 6379
    password: 123456
    database: 0
    timeout: 60000ms
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
